import {
  AlertCircle,
  AlertTriangle,
  Bell,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Edit,
  Eye,
  EyeOff,
  Info,
  Loader2,
  LogOut,
  Menu,
  MoreVertical,
  Plus,
  Search,
  Send,
  Settings,
  Trash,
  User,
  X,
  type Icon as LucideIcon,
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  logo: User,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  trash: Trash,
  menu: Menu,
  settings: Settings,
  user: User,
  add: Plus,
  warning: AlertTriangle,
  error: AlertCircle,
  check: Check,
  checkCircle: CheckCircle,
  info: Info,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  arrowRight: ChevronRight,
  help: Info,
  logout: LogOut,
  bell: Bell,
  search: Search,
  more: MoreVertical,
  send: Send,
  clock: Clock,
}
